"""Replay the Arcus deep-quote rule on Binance trade-by-trade history, month by month.

Same engine and rules as scripts/deep_quote_backtest.py (src/replay.simulate): post-only
quotes at mid ± d bps, requote on ≥1 bps drift, $25 clips, $100 inventory cap, RTT latency,
Arcus base-tier maker fee 0. Binance aggTrades carry no order book, so the replay never knows
our queue position: we fill only when a trade prints strictly through our price (the
conservative rule). Quotes are estimated from prints as in src/sweeps.py. Arcus tick size is
scaled to the Binance price level so rounding costs match in bps.

This measures the asset's own price behaviour under Arcus rules; it cannot reproduce Arcus's
particular order flow. Read it next to sweep_history.md and deep_quote_backtest.md.

Usage:
    .venv/bin/python scripts/binance_replay.py --pairs HYPEUSDT:HYPE-USD,NVDAUSDT:NVDA-USD --depths 3,5
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

from deep_quote_backtest import evaluate, market_specs  # noqa: E402
from src.replay import BBO, TRADE, Params, simulate  # noqa: E402
from src.sweeps import proxy_mid  # noqa: E402
from sweep_history import load_binance_month  # noqa: E402

DEFAULT = "HYPEUSDT:HYPE-USD,NVDAUSDT:NVDA-USD,SPYUSDT:SPY-USD,QQQUSDT:QQQ-USD,PAXGUSDT:GLD-USD,XAUUSDT:GLD-USD,XAGUSDT:SLV-USD,ZECUSDT:ZEC-USD"


def month_tape(zpath):
    """Interleave TRADE rows with proxy-BBO rows (bid/ask from latest taker sell/buy prints)."""
    ts, px, q, tb, _ = load_binance_month(zpath)
    o = np.argsort(ts, kind="stable")
    ts, px, q, tb = ts[o], px[o], q[o], tb[o]
    n = len(ts)
    # latest taker-buy price ~ ask, latest taker-sell price ~ bid
    ia = np.maximum.accumulate(np.where(tb, np.arange(n), -1))
    ib = np.maximum.accumulate(np.where(~tb, np.arange(n), -1))
    ok = (ia >= 0) & (ib >= 0)
    ask, bid = px[np.maximum(ia, 0)], px[np.maximum(ib, 0)]
    mid = proxy_mid(ts, px, tb)
    crossed = ask <= bid
    half = np.maximum(np.abs(ask - bid) / 2, mid * 1e-6)
    bid = np.where(crossed, mid - half, bid)
    ask = np.where(crossed, mid + half, ask)
    # a quote event only when the estimate moves (the strategy acts on quote events)
    moved = np.r_[True, (bid[1:] != bid[:-1]) | (ask[1:] != ask[:-1])]
    ok &= moved
    seq = np.arange(n, dtype=np.int64) * 2
    cols = dict(
        seq=np.concatenate([seq, seq[ok] + 1]),
        kind=np.concatenate([np.full(n, TRADE, np.int8), np.full(ok.sum(), BBO, np.int8)]),
        recv=np.concatenate([ts, ts[ok]]) * 1000,  # µs -> ns
        side=np.concatenate([np.where(tb, 1, -1).astype(np.int8), np.zeros(ok.sum(), np.int8)]),
        px=np.concatenate([px, bid[ok]]),
        sz=np.concatenate([q, ask[ok]]),
        aux=np.zeros(n + ok.sum()),
    )
    order = np.argsort(cols["seq"], kind="stable")
    return {k: v[order] for k, v in cols.items()}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pairs", default=DEFAULT, help="BINANCE_SYMBOL:ARCUS_MARKET,...")
    ap.add_argument("--depths", default="2,3,5,8")
    ap.add_argument("--rtt", type=float, default=200.0)
    ap.add_argument("--out", default=str(ROOT / "research" / "binance_replay.md"))
    a = ap.parse_args()
    specs = market_specs()
    depths = [float(x) for x in a.depths.split(",")]
    L = ["# Arcus deep-quote rule replayed on Binance history", "",
         f"Generated by `scripts/binance_replay.py` on {dt.datetime.now(dt.timezone.utc):%Y-%m-%d %H:%M} UTC. "
         f"RTT {a.rtt:g} ms, $25 clips, $100 max inventory, maker fee 0, trade-through fills only.", "",
         "| Binance symbol (Arcus) | depth bps | months | months +PnL | fills | notional $ | PnL $ | PnL bps | rs30 | worst month $ |",
         "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|"]
    for pair in a.pairs.split(","):
        sym, arc = pair.split(":")
        s = specs[arc]
        arc_px = float(s["markPrice"])
        zips = sorted((ROOT / "data" / "binance").glob(f"**/monthly/aggTrades/{sym}/*.zip"))
        if not zips:
            print(f"{sym}: no aggTrades downloaded", file=sys.stderr)
            continue
        acc = {d: [] for d in depths}
        for z in zips:
            tp = month_tape(z)
            ref_px = float(np.median(tp["px"][tp["kind"] == TRADE]))
            tick = float(s["tickSize"]) / arc_px * ref_px
            for d in depths:
                p = Params(depth_bps=d, requote_bps=1.0, clip_usd=25.0, max_pos_usd=100.0, rtt_ms=a.rtt,
                           tick=tick, step=1e-9, min_notional=5.0)
                r = evaluate(tp, simulate(tp, p), p)
                acc[d].append(r)
                print(f"{sym} {z.stem[-7:]} d={d:g}: fills={r['fills']} pnl=${r['pnl']:.2f} rs30={r['rs30']:.2f}",
                      file=sys.stderr, flush=True)
        for d in depths:
            rs = acc[d]
            notional = sum(r["notional"] for r in rs)
            pnl = sum(r["pnl"] for r in rs)
            w = [r["notional"] for r in rs if r["fills"]]
            rs30 = np.average([r["rs30"] for r in rs if r["fills"]], weights=w) if w else float("nan")
            L.append(f"| {sym} ({arc}) | {d:g} | {len(rs)} | {sum(r['pnl'] > 0 for r in rs)} | {sum(r['fills'] for r in rs)} | "
                     f"{notional:,.0f} | {pnl:.2f} | {pnl / notional * 1e4 if notional else float('nan'):.2f} | {rs30:.2f} | "
                     f"{min(r['pnl'] for r in rs):.2f} |")
        Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
