"""Does Binance's price explain which Arcus maker fills win?

For every Arcus maker fill (data/history/trades, scripts/pull_trade_history.py) overlapping
Binance trade data (data/binance/**/aggTrades, scripts/pull_binance.py):

  fair(t)  = Binance mid estimate at t (src/sweeps.proxy_mid) + rolling 10-min median of
             (Arcus print - Binance mid), i.e. the usual Arcus/Binance basis
  edge     = maker's price vs fair at the fill, bps (+ = sold above / bought below fair)
  outcome  = maker's result vs fair 30 s later, bps (Arcus maker fee 0)

Also reports lead-lag: correlation of 1 s mid changes, Arcus vs Binance at lags.

Usage:
    .venv/bin/python scripts/fair_value_study.py --pairs HYPE-USD:HYPEUSDT,NVDA-USD:NVDAUSDT
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

from src.sweeps import proxy_mid  # noqa: E402
from sweep_history import load_arcus, load_binance_month  # noqa: E402

DEFAULT = "HYPE-USD:HYPEUSDT,NVDA-USD:NVDAUSDT,SPY-USD:SPYUSDT,QQQ-USD:QQQUSDT,GLD-USD:XAUUSDT"
EDGE_BINS = [-1e9, -5, -2, -0.5, 0.5, 2, 5, 1e9]
EDGE_LABELS = ["< -5", "-5..-2", "-2..-0.5", "±0.5", "0.5..2", "2..5", "> 5"]
S = 1_000_000


def binance_series(sym, t0, t1):
    parts = []
    for z in sorted((ROOT / "data" / "binance").glob(f"**/aggTrades/{sym}/*.zip")):
        tag = z.stem.split("aggTrades-")[1]            # YYYY-MM or YYYY-MM-DD
        start = dt.datetime.fromisoformat(tag + ("-01" if len(tag) == 7 else "")).replace(tzinfo=dt.timezone.utc)
        if start.timestamp() * S > t1 or (start.timestamp() + 32 * 86400) * S < t0:
            continue
        ts, px, _, tb, _ = load_binance_month(z)
        parts.append((ts, px, tb))
    if not parts:
        return None, None
    ts = np.concatenate([p[0] for p in parts]); px = np.concatenate([p[1] for p in parts]); tb = np.concatenate([p[2] for p in parts])
    o = np.argsort(ts, kind="stable")
    ts, px, tb = ts[o], px[o], tb[o]
    keep = np.r_[ts[1:] != ts[:-1], True]  # one mid per microsecond
    return ts[keep], proxy_mid(ts, px, tb)[keep]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pairs", default=DEFAULT, help="ARCUS_MARKET:BINANCE_SYMBOL,...")
    ap.add_argument("--horizon", type=float, default=30.0)
    ap.add_argument("--out", default=str(ROOT / "research" / "fair_value_study.md"))
    a = ap.parse_args()
    H = int(a.horizon * S)
    L = ["# Binance fair value vs Arcus maker fills", "",
         f"Generated by `scripts/fair_value_study.py` on {dt.datetime.now(dt.timezone.utc):%Y-%m-%d %H:%M} UTC.",
         f"Edge = maker price vs fair (Binance mid + rolling Arcus basis) at the fill; outcome = vs fair {a.horizon:g} s later.",
         "Both in bps, notional-weighted. A fill with positive edge that keeps a positive outcome is money a",
         "quoter anchored to Binance could have earned at Arcus's 0 bps maker fee.", ""]
    for pair in a.pairs.split(","):
        arc, sym = pair.split(":")
        ts, px, q, tb, _ = load_arcus(arc)
        bts, bmid = binance_series(sym, ts[0], ts[-1])
        if bts is None:
            L.append(f"*{arc}: no overlapping Binance data*\n")
            continue
        m = (ts >= bts[0]) & (ts + H <= bts[-1])
        ts, px, q, tb = ts[m], px[m], q[m], tb[m]
        if len(ts) < 100:
            L.append(f"*{arc}: <100 overlapping fills*\n")
            continue
        i0 = np.searchsorted(bts, ts, side="right") - 1
        ih = np.searchsorted(bts, ts + H, side="right") - 1
        b0, bh = bmid[i0], bmid[ih]
        # trailing 10-min median of earlier prints only (closed="left" excludes the fill itself)
        basis = pd.Series(px / b0 - 1, index=pd.to_datetime(ts, unit="us")).rolling("10min", closed="left").median().to_numpy()
        ok = ~np.isnan(basis)
        ts, px, q, tb, b0, bh, basis = ts[ok], px[ok], q[ok], tb[ok], b0[ok], bh[ok], basis[ok]
        fair0, fairh = b0 * (1 + basis), bh * (1 + basis)
        sgn = np.where(tb, 1.0, -1.0)  # +1: maker sold
        edge = sgn * (px - fair0) / fair0 * 1e4
        out = sgn * (px - fairh) / fair0 * 1e4
        n = px * q
        span = f"{dt.datetime.fromtimestamp(ts[0] / S, dt.timezone.utc):%Y-%m-%d} → {dt.datetime.fromtimestamp(ts[-1] / S, dt.timezone.utc):%Y-%m-%d}"
        L += [f"## {arc} vs Binance {sym} ({span}, {len(ts):,} maker fills)", "",
              f"All fills: outcome {np.average(out, weights=n):+.2f} bps. Median |Arcus/Binance price ratio − 1| {np.nanmedian(np.abs(basis)) * 1e4:.1f} bps.", "",
              "| edge at fill (bps) | fills | notional % | outcome (bps) | share of fills that won |", "|---|---:|---:|---:|---:|"]
        cat = pd.cut(edge, EDGE_BINS, labels=EDGE_LABELS)
        for lab in EDGE_LABELS:
            s = np.asarray(cat == lab)
            if s.sum() >= 20:
                L.append(f"| {lab} | {s.sum():,} | {n[s].sum() / n.sum() * 100:.1f} | {np.average(out[s], weights=n[s]):+.2f} | {(out[s] > 0).mean() * 100:.0f}% |")
        # lead-lag on 1 s grid
        grid = np.arange(ts[0] // S + 1, ts[-1] // S) * S
        ga = px[np.clip(np.searchsorted(ts, grid, side="right") - 1, 0, None)]
        gb = bmid[np.clip(np.searchsorted(bts, grid, side="right") - 1, 0, None)]
        ra, rb = np.diff(np.log(ga)), np.diff(np.log(gb))
        lags = {}
        for k in (-3, -2, -1, 0, 1, 2, 3, 5):
            x, y = (ra[k:], rb[:len(rb) - k]) if k >= 0 else (ra[:k], rb[-k:])
            ok = (x != 0) | (y != 0)
            lags[k] = np.corrcoef(x[ok], y[ok])[0, 1] if ok.sum() > 100 else np.nan
        L += ["", "Correlation of Arcus 1 s change with Binance change k seconds earlier (k>0 = Binance leads):", "",
              "| k | " + " | ".join(str(k) for k in lags) + " |", "|---|" + "---:|" * len(lags),
              "| corr | " + " | ".join(f"{v:.2f}" for v in lags.values()) + " |", ""]
        print(f"{arc}: done", file=sys.stderr, flush=True)
    Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
