"""Queue-aware replay of a Binance-anchored quoter on recorded Arcus L2 tape.

Fair value = Binance mid (from aggTrades prints) observed `--feed-delay` ms after Binance's
own timestamp, times (1 + basis), where basis is the trailing 10-minute median of
(Arcus BBO mid / Binance mid − 1) using past data only. Quotes rest at fair ± d bps
(post-only, never crossing the Arcus touch) and requote when the target drifts ≥ requote bps.
Everything else as scripts/deep_quote_backtest.py; the unanchored rule runs alongside as a baseline.

Usage:
    .venv/bin/python scripts/fair_value_backtest.py --pairs HYPE-USD:HYPEUSDT --days 2026-09-19,2026-09-20
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

from deep_quote_backtest import evaluate, market_specs  # noqa: E402
from src.replay import BBO, Params, load_tape, simulate  # noqa: E402
from src.sweeps import proxy_mid  # noqa: E402
from sweep_history import load_binance_month  # noqa: E402

DEFAULT = "HYPE-USD:HYPEUSDT,NVDA-USD:NVDAUSDT,SPY-USD:SPYUSDT,QQQ-USD:QQQUSDT,GLD-USD:XAUUSDT,BTC-USD:BTCUSDT,ETH-USD:ETHUSDT"


def binance_days(sym, days):
    parts = []
    for d in days:
        for z in (ROOT / "data" / "binance").glob(f"**/daily/aggTrades/{sym}/{sym}-aggTrades-{d}.zip"):
            parts.append(load_binance_month(z))
    if not parts:
        return None
    ts = np.concatenate([p[0] for p in parts]); px = np.concatenate([p[1] for p in parts]); tb = np.concatenate([p[3] for p in parts])
    o = np.argsort(ts, kind="stable")
    ts, px, tb = ts[o], px[o], tb[o]
    mid = proxy_mid(ts, px, tb)
    keep = np.r_[mid[1:] != mid[:-1], True] & np.r_[ts[1:] != ts[:-1], True]  # only changes
    return ts[keep], mid[keep]


def fair_series(tp, bts_us, bmid, delay_ms):
    obs = bts_us * 1000 + int(delay_ms * 1e6)
    b = tp["kind"] == BBO
    t_a = tp["recv"][b]
    mid_a = (tp["px"][b] + tp["sz"][b]) / 2
    j = np.searchsorted(t_a, obs, side="right") - 1
    ok = j >= 0
    ratio = np.where(ok, mid_a[np.maximum(j, 0)] / bmid - 1, np.nan)
    basis = pd.Series(ratio, index=pd.to_datetime(obs, unit="ns")).rolling("10min", closed="left", min_periods=50).median().to_numpy()
    return obs, bmid * (1 + basis)  # NaN until the basis has warmed up -> no quoting


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pairs", default=DEFAULT, help="ARCUS_MARKET:BINANCE_SYMBOL,...")
    ap.add_argument("--days", default="2026-09-19,2026-09-20", help="Arcus tape days (Binance daily files must exist)")
    ap.add_argument("--depths", default="1,2,3,5")
    ap.add_argument("--rtt", type=float, default=200.0)
    ap.add_argument("--feed-delay", type=float, default=150.0, help="ms from a Binance print to our seeing it")
    ap.add_argument("--requote", type=float, default=0.5)
    ap.add_argument("--out", default=str(ROOT / "research" / "fair_value_backtest.md"))
    a = ap.parse_args()
    days = a.days.split(",")
    specs = market_specs()
    L = ["# Binance-anchored quoting, replayed on recorded Arcus L2", "",
         f"Generated by `scripts/fair_value_backtest.py` on {dt.datetime.now(dt.timezone.utc):%Y-%m-%d %H:%M} UTC. "
         f"Arcus days {a.days}; RTT {a.rtt:g} ms; Binance seen {a.feed_delay:g} ms late; requote ≥{a.requote:g} bps; "
         "$25 clips; $100 max inventory; maker fee 0.", "",
         "| market | rule | depth bps | fills | notional $ | PnL $ | PnL bps | rs30 | daily PnL $ | max inv $ |",
         "|---|---|---:|---:|---:|---:|---:|---:|---|---:|"]
    for pair in a.pairs.split(","):
        arc, sym = pair.split(":")
        prev = (dt.date.fromisoformat(days[0]) - dt.timedelta(days=1)).isoformat()
        b = binance_days(sym, [prev] + days)
        if b is None:
            print(f"{arc}: no Binance daily data", file=sys.stderr)
            continue
        tp = load_tape(arc, days)
        fair = fair_series(tp, *b, a.feed_delay)
        s = specs[arc]
        base = dict(requote_bps=a.requote, clip_usd=25.0, max_pos_usd=100.0, rtt_ms=a.rtt, tick=float(s["tickSize"]),
                    step=float(s["stepSize"]), min_notional=max(float(s["minOrderNotional"]), float(s["minOrderSize"]) * float(s["markPrice"])))
        for d in [float(x) for x in a.depths.split(",")]:
            for rule, extra in (("Binance-anchored", {"fair": fair}), ("Arcus mid", {})):
                p = Params(depth_bps=d, **base, **extra)
                r = evaluate(tp, simulate(tp, p), p)
                L.append(f"| {arc} | {rule} | {d:g} | {r['fills']} | {r['notional']:,.0f} | {r['pnl']:.2f} | {r['pnl_bps']:.2f} | "
                         f"{r['rs30']:.2f} | {', '.join(f'{x:.2f}' for x in r['daily'])} | {r['max_pos_usd']:.0f} |")
                print(f"{arc} {rule:16s} d={d:g}: fills={r['fills']} pnl=${r['pnl']:.2f} ({r['pnl_bps']:.2f} bps) "
                      f"rs30={r['rs30']:.2f} days={[round(float(x), 2) for x in r['daily']]}", file=sys.stderr, flush=True)
        Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
