"""Do trend and volatility filters separate winning from losing deep maker fills?

For every real Arcus maker fill 1–10 bps behind the touch (data/history/trades, estimate from
src/sweeps.py — validated for SPY/NVDA/QQQ/HYPE/BTC/ETH/ZEC), using only information available
before the fill:

  trend_5m / trend_1h  mid change over the prior 5 min / 1 h, signed from the maker's side:
                       + = the fill is WITH the trend (maker bought in an uptrend / sold in a downtrend)
  vol_5m               realized volatility of 1 s mid changes over the prior 5 min (bps per √s)

Outcome: maker realized spread at 30 s and 5 min (bps, Arcus maker fee 0). Results are split
by ISO week so a filter only counts if it helps week after week, not on average.

Usage:
    .venv/bin/python scripts/regime_study.py --markets SPY-USD,NVDA-USD
"""

from __future__ import annotations

import argparse
import datetime as dt
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

from src.sweeps import proxy_mid  # noqa: E402
from sweep_history import load_arcus  # noqa: E402

S = 1_000_000
DEFAULT = "SPY-USD,NVDA-USD,QQQ-USD,HYPE-USD,GLD-USD"


def fills_with_features(ts, px, q, tb, g):
    o = np.lexsort((np.where(tb, px, -px), g, ts))
    ts, px, q, tb, g = ts[o], px[o], q[o], tb[o], g[o]
    mid = proxy_mid(ts, px, tb)
    new = np.r_[True, g[1:] != g[:-1]]
    start = np.maximum.accumulate(np.where(new, np.arange(len(ts)), 0))
    pre = np.clip(start - 1, 0, None)
    m0 = mid[pre]
    sgn = np.where(tb, -1.0, 1.0)            # maker side: +1 maker bought (taker sold)
    depth = -sgn * (px - px[start]) / m0 * 1e4

    def mid_at(t):
        return mid[np.clip(np.searchsorted(ts, t, side="right") - 1, 0, None)]

    rs30 = sgn * (mid_at(ts + 30 * S) - px) / m0 * 1e4
    rs300 = sgn * (mid_at(ts + 300 * S) - px) / m0 * 1e4
    t_now = ts[pre]                             # state just before the sweep
    tr5 = sgn * (m0 / mid_at(t_now - 300 * S) - 1) * 1e4
    tr60 = sgn * (m0 / mid_at(t_now - 3600 * S) - 1) * 1e4
    # 5-min realized vol on a 1 s grid, computed once and looked up
    grid = np.arange(ts[0] // S, ts[-1] // S + 1) * S
    gm = mid[np.clip(np.searchsorted(ts, grid, side="right") - 1, 0, None)]
    r = np.r_[0.0, np.diff(np.log(gm))] * 1e4
    vol = np.sqrt(pd.Series(r ** 2).rolling(300, min_periods=60).mean().to_numpy())
    vol5 = vol[np.clip((t_now - grid[0]) // S, 0, len(vol) - 1)]
    ok = (start > 0) & (depth > 1.0) & (depth <= 10.0) & (ts + 300 * S <= ts[-1]) & (t_now - 3600 * S >= ts[0])
    return pd.DataFrame(dict(ts=ts[ok], depth=depth[ok], n=(px * q)[ok], rs30=rs30[ok], rs300=rs300[ok],
                             tr5=tr5[ok], tr60=tr60[ok], vol5=vol5[ok]))


def wavg(d, col):
    return np.average(d[col], weights=d["n"]) if len(d) else np.nan


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--markets", default=DEFAULT)
    ap.add_argument("--from-date", default="2026-07-20")
    ap.add_argument("--out", default=str(ROOT / "research" / "regime_study.md"))
    a = ap.parse_args()
    start_us = int(dt.datetime.fromisoformat(a.from_date).replace(tzinfo=dt.timezone.utc).timestamp()) * S
    L = ["# Trend and volatility vs deep maker fills (Arcus history)", "",
         f"Generated by `scripts/regime_study.py` on {dt.datetime.now(dt.timezone.utc):%Y-%m-%d %H:%M} UTC, fills from "
         f"{a.from_date}, 1–10 bps behind the touch. Cells: notional-weighted maker result in bps at 30 s / 5 min "
         "(`weeks+` = weeks where that group beat the other group at 5 min).", ""]
    for m in a.markets.split(","):
        df = fills_with_features(*load_arcus(m))
        df = df[df.ts >= start_us]
        df["week"] = pd.to_datetime(df.ts, unit="us").dt.strftime("%G-W%V")
        L += [f"## {m} ({len(df):,} fills)", "", "| split | group | fills | 30 s | 5 min | weeks+ |", "|---|---|---:|---:|---:|---:|"]
        splits = {
            "5-min trend": np.where(df.tr5 > 0, "with trend", "against trend"),
            "1-h trend": np.where(df.tr60 > 0, "with trend", "against trend"),
            "5-min volatility": np.where(df.vol5 > df.groupby("week").vol5.transform("median"), "high vol", "low vol"),
        }
        for name, grp in splits.items():
            df["g"] = grp
            labels = sorted(set(grp))
            wk = df.groupby(["week", "g"]).apply(lambda d: wavg(d, "rs300"), include_groups=False).unstack()
            for lab in labels:
                other = [x for x in labels if x != lab]
                wins = int((wk[lab] > wk[other[0]]).sum()) if other else 0
                d = df[df.g == lab]
                L.append(f"| {name} | {lab} | {len(d):,} | {wavg(d, 'rs30'):+.2f} | {wavg(d, 'rs300'):+.2f} | {wins}/{len(wk)} |")
        L.append("")
        print(f"{m}: {len(df):,} fills", file=sys.stderr, flush=True)
    Path(a.out).write_text("\n".join(L) + "\n")
    print(f"wrote {a.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
