"""Month-by-month maker edge by sweep depth, on Arcus 30-day history and Binance multi-year tapes.

Sources
  arcus:<MARKET>     data/history/trades/<MARKET>.jsonl.gz  (scripts/pull_trade_history.py)
  binance:<SYMBOL>   data/binance/**/aggTrades/<SYMBOL>/*.zip (scripts/pull_binance.py)

Uses src/sweeps.py (quote-free proxy, validated against true BBO in FINDINGS.md: trustworthy
for depth buckets beyond the touch on liquid tapes, conservative in magnitude; not for the
touch bucket on thin markets). Fees are Arcus base tier: maker 0 bps, so rs30 is the net edge.

Usage:
    .venv/bin/python scripts/sweep_history.py --sources arcus:HYPE-USD,binance:HYPEUSDT
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
import gzip
import io
import json
import sys
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src import sweeps  # noqa: E402

DEFAULT = ("arcus:HYPE-USD,arcus:SPY-USD,arcus:NVDA-USD,arcus:QQQ-USD,arcus:BTC-USD,arcus:ETH-USD,"
           "binance:HYPEUSDT,binance:NVDAUSDT,binance:SPYUSDT,binance:QQQUSDT,binance:XAUUSDT,"
           "binance:XAGUSDT,binance:PAXGUSDT,binance:ZECUSDT")


def load_arcus(market):
    f = ROOT / "data" / "history" / "trades" / f"{market}.jsonl.gz"
    rows = []
    with gzip.open(f, "rt") as fh:
        for t in map(json.loads, fh):
            rows.append((t["timestamp"], float(t["price"]), float(t["size"]), t["side"] == "BUY", t["sequenceNumber"]))
    a = np.array(rows, dtype=float)
    return a[:, 0].astype(np.int64), a[:, 1], a[:, 2], a[:, 3].astype(bool), a[:, 4].astype(np.int64)


def load_binance_month(zpath):
    with zipfile.ZipFile(zpath) as z:
        raw = z.read(z.namelist()[0])
    header = 0 if not raw[:1].isdigit() else None  # futures files carry a header, spot files don't
    df = pd.read_csv(io.BytesIO(raw), header=header, usecols=[1, 2, 5, 6])
    df.columns = ["price", "qty", "time", "buyer_maker"]
    ts = df["time"].to_numpy(np.int64)
    ts = np.where(ts < 10**14, ts * 1000, ts)  # ms -> µs (spot switched to µs in 2025)
    taker_buy = ~df["buyer_maker"].astype(str).str.lower().eq("true").to_numpy()
    a = df[["price", "qty"]].to_numpy(float)
    # one taker order = consecutive prints with the same timestamp and side
    key = ts * 2 + taker_buy
    grp = np.cumsum(np.r_[True, key[1:] != key[:-1]])
    return ts, a[:, 0], a[:, 1], taker_buy, grp


def months_for(src):
    kind, name = src.split(":")
    if kind == "arcus":  # ~12 weeks of history: split by ISO week
        ts, px, q, tb, g = load_arcus(name)
        wk = np.array([dt.datetime.fromtimestamp(t / 1e6, dt.timezone.utc).strftime("%G-W%V") for t in ts[::1]])
        for w in dict.fromkeys(wk):
            s = wk == w
            if s.sum() >= 200:
                yield w, (ts[s], px[s], q[s], tb[s], g[s])
        return
    for z in sorted((ROOT / "data" / "binance").glob(f"**/monthly/aggTrades/{name}/*.zip")):
        yield z.stem.rsplit("-", 2)[-2] + "-" + z.stem.rsplit("-", 1)[-1], load_binance_month(z)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--sources", default=DEFAULT)
    ap.add_argument("--out", default=str(ROOT / "research" / "sweep_history.md"))
    a = ap.parse_args()
    labels = [b[2] for b in sweeps.BUCKETS]
    rows = []
    for src in a.sources.split(","):
        pooled = {lab: [0.0, 0.0, 0] for lab in labels}  # sum(rs*n), sum(n), fills
        for month, (ts, px, q, tb, g) in months_for(src):
            _, dep, rs, n = sweeps.sweep_table(ts, px, q, tb, g)
            res = {lab: (c, v) for lab, c, v in sweeps.by_bucket(dep, rs, n)}
            for lo, hi, lab in sweeps.BUCKETS:
                s = (dep > lo) & (dep <= hi) if lo >= 0 else (np.abs(dep) <= hi)
                pooled[lab][0] += float((rs[s] * n[s]).sum()); pooled[lab][1] += float(n[s].sum()); pooled[lab][2] += int(s.sum())
            rows.append((src, month, len(ts), res))
            print(f"{src} {month}: " + "  ".join(f"{k} {v[1]:+.2f}" for k, v in res.items()), file=sys.stderr, flush=True)
        rows.append((src, "POOLED", 0, {k: (v[2], v[0] / v[1]) for k, v in pooled.items() if v[2] >= 10}))

    L = ["# Maker edge by sweep depth over history", "",
         f"Generated by `scripts/sweep_history.py` on {dt.datetime.now(dt.timezone.utc):%Y-%m-%d %H:%M} UTC.",
         "Cells: notional-weighted maker realized spread at 30 s (bps, Arcus maker fee 0) for fills at that",
         "depth beyond the sweep's first print; `n` fills in brackets. Touch column is unreliable on thin",
         "tapes (see FINDINGS.md). Binance rows describe the asset on Binance, not Arcus's own flow.", "",
         "| source | month | prints | " + " | ".join(labels) + " |",
         "|---|---|---:|" + "---:|" * len(labels)]
    pos = {}
    for src, month, n, res in rows:
        cells = [f"{res[lab][1]:+.2f} ({res[lab][0]})" if lab in res else "—" for lab in labels]
        L.append(f"| {src} | {month} | {n:,} | " + " | ".join(cells) + " |")
        if month != "POOLED":
            for lab in labels:
                if lab in res and res[lab][0] >= 30:
                    t = pos.setdefault((src, lab), [0, 0])
                    t[0] += res[lab][1] > 0; t[1] += 1
    L += ["", "## Periods positive (months for Binance, ISO weeks for Arcus; buckets with ≥30 fills)", "", "| source | " + " | ".join(labels) + " |",
          "|---|" + "---|" * len(labels)]
    for src in dict.fromkeys(r[0] for r in rows):
        L.append(f"| {src} | " + " | ".join(f"{pos[(src, lab)][0]}/{pos[(src, lab)][1]}" if (src, lab) in pos else "—" for lab in labels) + " |")
    Path(a.out).write_text("\n".join(L) + "\n")
    with open(Path(a.out).with_suffix(".csv"), "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["source", "month", "bucket", "fills", "rs30_bps"])
        for src, month, _, res in rows:
            for lab, (c, v) in res.items():
                w.writerow([src, month, lab, c, round(v, 4)])
    print(f"wrote {a.out}", file=sys.stderr)


if __name__ == "__main__":
    main()
